name: 📝 Documentation Request
description: Suggest extra documentation for this project
title: "[Documentation Request]: "
labels: ["type: documentation"]
assignees:
  - Celerium
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: checkboxes
    id: ReadME
    attributes:
      label: README
      description: Have you read our README
      options:
        - label: "[ReadMe](https://github.com/Celerium/xxxREPONAMExxx/blob/main/README.md)"
  - type: checkboxes
    id: WebDocumentation
    attributes:
      label: Web Documentation
      description: Have you read the online documentation
      options:
        - label: "[Documentation](https://Celerium.github.io/xxxREPONAMExxx/)"
  - type: checkboxes
    id: PowerShellHelp
    attributes:
      label: PowerShell Help
      description: Have you read the help output?
      options:
        - label: "Get-Help Get-xxxModulePrefixxxx<RESOURCES-NAME> -Full"
  - type: textarea
    id: DocumentationRequest
    attributes:
      label: Documentation Request
      description: What would you like to see more documentation around?
      render: Text
  - type: textarea
    id: ExistingIssue
    attributes:
      label: Existing Issue?
      description: Please describe or link.
      value: "Issue: #12345
        Link: <https://github.com/Celerium/xxxREPONAMExxx/issues/1>
        "
  - type: textarea
    id: NewDocumentation
    attributes:
      label: New Documentation
      description: A clear and concise description of what you want to happen.